-- Maharashtra seed restaurants (Bangalore)
INSERT INTO public.restaurants (name, description, cuisine_state, type, status, image_url, must_try_dishes, maps_link)
VALUES
('Suryawanshi', 'An absolute gem for meat lovers, specializing in fiery Kolhapuri thalis, rich Malvani seafood, and their iconic Pandhra and Tambda Rassa.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=1600', 'Kolhapuri Mutton Thali, Bombil Fry', 'https://www.google.com/maps/search/Suryawanshi+Whitefield+Bangalore'),
('Purnabramha', 'The largest Maharashtrian restaurant chain in the city, known for its regal, authentic vegetarian thalis and festive dishes served in a traditional setting.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Puran Poli, Shrikhand Puri Thali', 'https://www.google.com/maps/search/Purnabramha+HSR+Layout+Bangalore'),
('Rajvardhan Foods', 'A beloved neighborhood joint in Jayanagar bustling with locals queuing up for authentic Kande Pohe, Sabudana Khichdi, and perfectly spiced Misal Pav.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Sabudana Vada, Misal Pav', 'https://www.google.com/maps/search/Rajvardhan+Foods+Jayanagar+Bangalore'),
('Maratha Darshan', 'A legendary, no-frills eatery in Koramangala that serves some of the most comforting and intensely flavorful home-style Maratha meat curries.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1600', 'Chicken Masala, Mutton Bhakri', 'https://www.google.com/maps/search/Maratha+Darshan+Koramangala+Bangalore'),
('Peshwa', 'Brings the authentic flavors of Pune to Bangalore. Famous for its Kothimbir Vadi, Thalipeeth, and classic Puneri-style vegetarian meals.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=1600', 'Puneri Thali, Kothimbir Vadi', 'https://www.google.com/maps/search/Peshwa+Koramangala+Bangalore'),
('Mast Marathi', 'A modern quick-service outlet offering a wide array of authentic Maharashtrian snacks, from buttery Vada Pavs to hearty Pithla Bhakri.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1610147323479-a7fb11ffd5dd?q=80&w=1600', 'Vada Pav, Pithla Bhakri', 'https://www.google.com/maps/search/Mast+Marathi+HSR+Layout+Bangalore'),
('Mumbai Xpress', 'A vegetarian street food haven that flawlessly replicates the iconic taste of Mumbai''s Chowpatty, serving buttery Pav Bhaji and loaded sandwiches.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=1600', 'Pav Bhaji, Bombay Sandwich', 'https://www.google.com/maps/search/Mumbai+Xpress+Indiranagar+Bangalore'),
('Gawran Misal', 'A paradise for spice enthusiasts, specializing in authentic, sweat-inducing Kolhapuri Misal served with soft pav and cooling Taak (buttermilk).', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Kolhapuri Misal, Taak', 'https://www.google.com/maps/search/Gawran+Misal+Koramangala+Bangalore'),
('Khandesh', 'Focuses on the fiercely spicy and aromatic cuisine of the Khandesh region of Maharashtra, offering incredible mutton gravies and rustic flatbreads.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1600', 'Khandeshi Mutton Curry, Bajra Bhakri', 'https://www.google.com/maps/search/Khandesh+BTM+Layout+Bangalore'),
('Aamchi Mumbai', 'A pocket-friendly destination for students and working professionals craving genuine Mumbai street food staples like Vada Pav and Dabeli.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Vada Pav, Sabudana Vada', 'https://www.google.com/maps/search/Aamchi+Mumbai+BTM+Layout+Bangalore'),
('Maharashtra Mandal Canteen', 'An old-school cultural institution in Gandhinagar running a canteen that serves incredibly affordable, homestyle Maharashtrian daily meals.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=1600', 'Maharashtrian Veg Thali, Shira', 'https://www.google.com/maps/search/Maharashtra+Mandal+Gandhinagar+Bangalore'),
('Gavkari', 'Translating to "villager", this spot excels at delivering authentic rural Maharashtrian non-vegetarian preparations with robust, earthy spice blends.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600', 'Gavkari Mutton Thali, Solkadhi', 'https://www.google.com/maps/search/Gavkari+Marathahalli+Bangalore'),
('Dada''s Vada Pav', 'A legendary kiosk that many argue serves the absolute best, most authentic Mumbai-style Vada Pav in all of Bangalore, accompanied by fiery garlic dry chutney.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1610147323479-a7fb11ffd5dd?q=80&w=1600', 'Classic Vada Pav, Cheese Vada Pav', 'https://www.google.com/maps/search/Dadas+Vada+Pav+Indiranagar+Bangalore'),
('Kolhapuri Thaat', 'Brings the royal, spicy heritage of Kolhapur to Bangalore plates. Known for its deeply flavored meat rassa and authentic thalis.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1626295551846-95f0393f95e2?q=80&w=1600', 'Tambada Rassa, Chicken Sukka', 'https://www.google.com/maps/search/Kolhapuri+Thaat+Bangalore'),
('Pune Misal House', 'Dedicated almost entirely to perfecting the art of Puneri Misal — which is slightly milder but incredibly flavorful compared to its Kolhapuri cousin.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Puneri Misal Pav, Kande Pohe', 'https://www.google.com/maps/search/Pune+Misal+House+Rajajinagar+Bangalore'),
('Swaad of Maharashtra', 'A cozy restaurant offering a highly comforting menu of authentic Maharashtrian dishes, celebrated for their fresh Modaks during festive seasons.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Ukadiche Modak, Masale Bhaat', 'https://www.google.com/maps/search/Swaad+of+Maharashtra+JP+Nagar+Bangalore'),
('Mumbai Tiffin', 'Recreates the nostalgia of Mumbai dabbawalas by serving authentic, homestyle Usal, Matki Sabzi, and soft, freshly baked pavs.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=1600', 'Usal Pav, Sabudana Khichdi', 'https://www.google.com/maps/search/Mumbai+Tiffin+Jayanagar+Bangalore'),
('Mejwani', 'A fantastic spot for coastal Maharashtrian (Malvani) cuisine, offering incredible fresh fish fries coated in rava (semolina) and tangy fish curries.', 'Maharashtra', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1626295551846-95f0393f95e2?q=80&w=1600', 'Surmai Rava Fry, Malvani Chicken', 'https://www.google.com/maps/search/Mejwani+Koramangala+Bangalore'),
('Bhairunath Ice Cream & Misal House', 'A quirky but highly authentic combination offering intensely spicy, flavorful Misal Pav followed directly by their soothing, house-made ice creams.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Special Misal Pav, Mattha', 'https://www.google.com/maps/search/Bhairunath+Misal+House+BTM+Bangalore'),
('Gokhale Veg', 'A humble, highly-rated eatery in Malleswaram serving simple, impeccable Maharashtrian breakfast staples loved by the Marathi diaspora.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1610147323479-a7fb11ffd5dd?q=80&w=1600', 'Thalipeeth, Piyush', 'https://www.google.com/maps/search/Gokhale+Veg+Malleswaram+Bangalore'),
('Shivaji Vada Pav', 'A classic, bustling stall that serves perfectly crispy vadas encased in soft pav, relying on authentic Mumbai spices and absolutely no fuss.', 'Maharashtra', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Classic Vada Pav', 'https://www.google.com/maps/search/Shivaji+Vada+Pav+Jayanagar+Bangalore');
