-- Tamil Nadu seed restaurants (Bangalore)
INSERT INTO public.restaurants (name, description, cuisine_state, type, status, image_url, must_try_dishes, maps_link)
VALUES
('Anjappar Chettinad Restaurant', 'A global ambassador of Chettinad cuisine, bringing the legendary, spice-heavy flavors and robust meat curries of Karaikudi to Bangalore.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=1600', 'Chettinad Chicken Roast, Mutton Sukka', 'https://www.google.com/maps/search/Anjappar+Koramangala+Bangalore'),
('Dindigul Thalappakatti', 'Famous for their historically protected, distinct Seeraga Samba rice biryani that relies on a secret spice blend dating back to 1957.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?q=80&w=1600', 'Thalappakatti Mutton Biryani, Black Pepper Chicken', 'https://www.google.com/maps/search/Dindigul+Thalappakatti+Indiranagar+Bangalore'),
('Murugan Idli Shop', 'A legendary Madurai institution renowned for its incredibly soft, sticky idlis, signature spicy podis, and authentic Jigarthanda.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1610147323479-a7fb11ffd5dd?q=80&w=1600', 'Ghee Podi Idli, Sweet Pongal, Jigarthanda', 'https://www.google.com/maps/search/Murugan+Idli+Shop+Jayanagar+Bangalore'),
('Junior Kuppanna', 'Pioneers of Kongu Nadu cuisine in the city, known for their unique use of Copra (dry coconut) and the iconic Pallipalayam chicken.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1600', 'Pallipalayam Chicken, Mutton Biryani', 'https://www.google.com/maps/search/Junior+Kuppanna+Koramangala+Bangalore'),
('Ponnusamy Restaurant', 'An iconic Chennai import serving massive, feast-like Bahubali thalis and fiercely traditional Chettinad preparations like Pigeon fry.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600', 'Bahubali Thali, Nattu Kozhi Roast', 'https://www.google.com/maps/search/Ponnusamy+Restaurant+Bangalore'),
('Ambur Star Briyani', 'Brings the authentic, mildly spiced, and deeply aromatic Arcot Nawab style biryani from Ambur directly to Bangalore plates.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?q=80&w=1600', 'Ambur Mutton Biryani, Chicken 65', 'https://www.google.com/maps/search/Ambur+Star+Briyani+BTM+Bangalore'),
('New Sree Krishna Kafe', 'A legendary, simplistic Koramangala spot offering pure, unadulterated Tamil Brahmin style meals served piping hot on banana leaves.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Tamil Meals, Vatha Kuzhambu', 'https://www.google.com/maps/search/New+Sree+Krishna+Kafe+Koramangala+Bangalore'),
('A2B - Adyar Ananda Bhavan', 'A household name offering highly reliable Chennai-style tiffin items, filter coffee, and an expansive range of traditional Tamil sweets.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Mini Tiffin, Ghee Roast Dosa', 'https://www.google.com/maps/search/A2B+Adyar+Ananda+Bhavan+Bangalore'),
('Hotel Saravana Bhavan', 'The absolute gold standard for global Tamil vegetarian fare, serving textbook-perfect dosas and authentic Chennai-style meals.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=1600', 'Saravana Bhavan Meals, Filter Coffee', 'https://www.google.com/maps/search/Hotel+Saravana+Bhavan+Bangalore'),
('Madurai Kumar Mess', 'Specializes in rustic Madurai non-vegetarian street food, famed across the city for its heavy, meat-laden Kari Dosa and Kola Urundai.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600', 'Mutton Kari Dosa, Kola Urundai', 'https://www.google.com/maps/search/Madurai+Kumar+Mess+Bangalore'),
('Savya Rasa', 'A premium dining experience that meticulously recreates heritage recipes from various culinary regions of Tamil Nadu, including Kongunadu and Chettinad.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1626295551846-95f0393f95e2?q=80&w=1600', 'Meen Kuzhambu, Bun Parotta', 'https://www.google.com/maps/search/Savya+Rasa+Koramangala+Bangalore'),
('Iyer Mess', 'A tucked-away Malleswaram gem that feels like dining in a Tamil home, serving simplistic, phenomenal vegetarian meals for decades.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600', 'Unlimited Tamil Meals, Payasam', 'https://www.google.com/maps/search/Iyer+Mess+Malleswaram+Bangalore'),
('Mylapore Cafe', 'Recreates the traditional flavors of Chennai''s cultural hub, offering authentic Kumbakonam degree coffee and excellent tiffin varieties.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Kumbakonam Degree Coffee, Medu Vada', 'https://www.google.com/maps/search/Mylapore+Cafe+Whitefield+Bangalore'),
('Salem R R Biriyani', 'Offers a uniquely spicy and flavorful biryani originating from Salem, featuring tender meat and a distinctly rich, localized spice profile.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?q=80&w=1600', 'Salem Biryani, Chilli Chicken', 'https://www.google.com/maps/search/Salem+RR+Biriyani+Bangalore'),
('Nagercoil Arya Bhavan', 'Showcases the unique culinary crossover of southern Tamil Nadu, offering robust, deeply flavorful vegetarian curries and excellent parottas.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=1600', 'Parotta Kurma, Nagercoil Meals', 'https://www.google.com/maps/search/Nagercoil+Arya+Bhavan+Bangalore'),
('Madurai Idly Shop', 'A fast-casual spot that perfectly executes the simple art of pillowy Madurai idlis served with an array of traditional, fiery chutneys.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1610147323479-a7fb11ffd5dd?q=80&w=1600', 'Thatte Idli, Onion Uttapam', 'https://www.google.com/maps/search/Madurai+Idly+Shop+Bangalore'),
('Aasife Biriyani', 'A heavyweight in the Chennai biryani scene now serving its signature rich flavors, tender meat, and excellent Mughlai-Tamil fusion sides in Bangalore.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?q=80&w=1600', 'Aasife Chicken Biryani, Tandoori Chicken', 'https://www.google.com/maps/search/Aasife+Biriyani+Bangalore'),
('Karaikudi Chettinad Mess', 'Delivers heavy, unapologetically spice-laden Chettinad gravies and phenomenal Nattu Kozhi (country chicken) preparations in a simple setting.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600', 'Chettinad Meals, Nattu Kozhi Rasam', 'https://www.google.com/maps/search/Karaikudi+Chettinad+Mess+Bangalore'),
('Kovai Kitchen', 'Focuses on the distinct flavors of Coimbatore, bringing excellent Kongu-style biryanis and peppery meat roasts to a modern dining space.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=1600', 'Kovai Chicken Roast, Seeraga Samba Biryani', 'https://www.google.com/maps/search/Kovai+Kitchen+Bangalore'),
('Chennai Tiffins', 'A highly reliable, quick-service joint serving classic Tamil street food staples, including fantastic Kothu Parotta and piping hot Pongal.', 'Tamil Nadu', 'veg', 'approved', 'https://images.unsplash.com/photo-1589301760014-d929f39ce9de?q=80&w=1600', 'Kothu Parotta, Ven Pongal', 'https://www.google.com/maps/search/Chennai+Tiffins+Bangalore'),
('Trichy Banana Leaf', 'Offers hearty, traditional Tamil meals and fiery meat roasts served the old-fashioned way on fresh banana leaves.', 'Tamil Nadu', 'nonveg', 'approved', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600', 'Banana Leaf Meals, Mutton Pepper Fry', 'https://www.google.com/maps/search/Trichy+Banana+Leaf+Bangalore');